# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161031_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='relation_user',
            new_name='created_by',
        ),
    ]
